
GOOGLE_DRIVE_FOLDER_ID = "1IB8TbwUYMqu3JElebpg0ctpPcQ4IfSBe"

[GOOGLE_DRIVE_CREDENTIALS]
type = "service_account"
project_id = "my-food-459018"
private_key_id = "5d9e8c9c35558f9c37877cf183815b012cd69940"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCMZljoQ8aDS1Ok
96YAgDqo9Hz9C6lN8fPu8ZmNehQn0VyTln68Wy5i2EOQZk+VI9QS+F+KPBGYCHSZ
GyWTlHp2n4trSMY278UqhL3soqzPK+5UNzomQUEyagZa01SZO8sZTvG/+b92r4YJ
aQWwRxjdvuRNHEZgMZVsN8TdemoHDBrZ6k/mPKlDjag45L2w7l+aJN7IFQZeudMD
1yNnUfDvWACCljI5HbYgPmrn/XZ3PQTo/C0+l0xXdFTSieSCMx9AZJdUWsDZFI5e
Oayvmsj4GYOEHRBolTMTdP1W6+Klc+I8O31TTZuqDuvdJty4MdlU9SEyNg91YE1A
vYuIeDCJAgMBAAECggEAAsI3OeoXVj4BHjHPq9JuhKJtgHHYa+ZcBlxY1Gowh5yX
dXQXWFIGKhhJJzxRZj2/2sxmoSz/ZKsO3RwcJly8SsTQAhsaFPCBYY2zPHlGTLmh
NfunUM2HBMucmsUsqX2epsgcW9Wst3M+XpnhtsYw2i44PBPOW1vCDZArdgrD7FCU
amBIDFtRAwNI6YKHe45jE0DBJk92mjkhUbngbkJUr2qRqiplkfOaF/hEEtc64kSK
2aeMBrvpDkWnCFuSVN0M3w2uDcAW0oTRIELRV8XPug+pqLBG4pR9IghUMyIRR2rD
TCVBmUwA/4bR6zZUGwGNxjQCFgWuKu1NwhsH3wKyQQKBgQC+QDo176DZdcCTBGt+
rQ4KjhrnG0npvYV/E3nQUeaFFRPG6DE+H/qToPh0UwEYY+t5Z9p24y3KrDxGV1h6
cMzQrt8CHkiJ6JX0pFY/1Q8Y5CMr0y+r5uCh6dV3fPxvHdFpoYYQ8m/6jcu5mK7V
j4LC9wYfZJb9Hokd33AgjapCwQKBgQC867idgpnZkAfLVSN9NPTwrok8uJ/jugzI
VVm9Yg5I9HuXkLk/rGQcA3axxEgso+mbCcVj9rbsjApDWBvD49j8atxuGjO7R3no
eltyxEQAwD8xcV91JtYMPfuwIzlQ00Mzsio+91sIJGQ92X82e2VIupo32MBGfs48
Oqs/yBaHyQKBgQCZtKJS+SrnBe9z19pRGdeCR5UMqktpAKleJYoA+GpZktHLncRL
AOMdaqvQr07vOasBBxrFen2AhO6dlevx4DhZUS7zMyw/3x1n7W2RXL05yvdvbMvT
AlDx/01roBsCWwDZapo6DuTRdMXnSKfX+n4WriTQMCCcl5MIA4E/i7THAQKBgCHm
aopZFSJlJgDmliexiQJnT1kGCCrlB8YrCp9hKQ8OT98yqQsz9ALS3Emp3wmjoBeh
+Tmm28w2lODgvpq4GAezZTqcmQvSF54P1rkRXuKDnNNSdL6g6Wfo93Dz4SUPw89S
+SGzYTJk1VgD3z/3hIU4dtPuoRIFTxyfqnsXfHOBAoGAHe3Ecn7ZmpEzhWVrq3Iu
nk0ZxeYCBnlC0EsCp1d61CfZvcyL/onLMyVrvc4dlyNcDzGuPvnj0LC+yGyAU2bp
BUOq+UmfRUjT3AzTDQRwAf9MG7BKiQyEixnTYLOyUAs2tlbJWiPpuwhyLlSKJPOi
XfD2D88aH1TjvgRlW9zmg1M=
-----END PRIVATE KEY-----"""
client_email = "food-app@my-food-459018.iam.gserviceaccount.com"
client_id = "106647326021758338171"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/food-app%40my-food-459018.iam.gserviceaccount.com"
