"""Update shopping_list table schema

Revision ID: e8bfb2d4cc50
Revises: 94784dba1688
Create Date: 2025-11-09 21:33:47.397266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8bfb2d4cc50'
down_revision: Union[str, None] = '94784dba1688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('source', sa.String(length=500), nullable=True))
    op.alter_column('shopping_list', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_shopping_list_is_checked'), 'shopping_list', ['is_checked'], unique=False)
    op.drop_column('shopping_list', 'is_extra')
    op.drop_column('shopping_list', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shopping_list', sa.Column('is_extra', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shopping_list_is_checked'), table_name='shopping_list')
    op.alter_column('shopping_list', 'quantity',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('shopping_list', 'source')
    # ### end Alembic commands ###
